### ISSUE TITLE
Question: Passing Header Values from Shared PCL

### ISSUE THREAD

**Issue by ryanmendoza** [albertoms/xamarin-webview-with-custom-headers#1]
Hey there, this works like a charm for what you documented that it should do. One question, though... how can I pass header values from the shared project to these custom renderers in the iOS and Android projects?

**Comment by luisguerrerolab** [comment]
Hi, @ryanmendoza 

I've updated the project including an example that shows how to send parameters from shared code.

I hope this helps.

Cheers.

**Comment by ryanmendoza** [comment]
@albertoms looks great, thanks!
