### ISSUE TITLE
Invoke CustomWebViewRenderer after setting my WebView Source

### ISSUE THREAD

**Issue by mmehdidehghani** [albertoms/xamarin-webview-with-custom-headers#2]
Hi @albertoms 
Thanks a lot for sharing the great code.
I'm new in xamarin.forms
Could you please help me? :  🌹🌹
When my xaml page loaded, customwebview source is null. I set that when a button have been clicked, my url would be assign to my customwebview' source. I checked and found that CustomWebViewRenderer  class invoke for the first time (when my source is null).
How can I set header when URL would be assign for my customwebview; source ?

I don't know I could explain exact mean my issue to you? 🙈🙏🏻

Best regards

**Comment by luisguerrerolab** [comment]
Hi, @mmehdidehghani:

It would be helpful if you share the code you are currently working on.

From what I understood, you change the `WebView.URL` property when a button is clicked, so you will need to implement an event handler for that click in order to change the property's value.
