### ISSUE TITLE
How to implement an ActivityIndicator to this setup

### ISSUE THREAD

**Issue by SlimboTimbo** [albertoms/xamarin-webview-with-custom-headers#4]
Thank you so much for sharing your code, it works like a charm!

Quick question though - how would you implement an AcitivtyIndicator to this setup? Would you include it in the custom renderer or keep it within the View?

**Comment by luisguerrerolab** [comment]
Hi, @SlimboTimbo 

You can use the events that `UIWebView` has:
- LoadStarted (show AI)
- LoadFinished (hide AI)
- LoadError (hide AI, to avoid keeping AI running if something bad happens)

And call your cross-platform service that shows the ActivityIndicator from the corresponding event handlers.

**Note: be aware that UIWebView is now deprecated and you should migrate to `WKWebView` as soon as possible.**
